import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

import Pr from './_trpc/TRPCProvider'
import NavigationBar from '@/components/Navbar/NavigationBar'

const inter = Poppins({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    preload: true,
})

export const metadata: Metadata = {
    title: 'LookAtYourServer',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Pr>
                    <div>{children}</div>
                </Pr>
            </body>
        </html>
    )
}
